# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:08
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolCalendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('tekst', models.TextField(blank=True)),
                ('startdatum', models.DateField()),
                ('einddatum', models.DateField(blank=True, null=True)),
                ('plaats', models.CharField(blank=True, max_length=200)),
                ('doelgroep', multiselectfield.db.fields.MultiSelectField(choices=[('KS', 'Kleuters'), ('BS', 'Basisschool'), ('OB', 'Onderbouw'), ('MS', 'Middelbare school'), ('MB', 'Middenbouw'), ('BB', 'Bovenbouw'), ('AA', 'allen')], max_length=20)),
                ('publiek', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['startdatum'],
                'verbose_name_plural': 'SchoolCalendar',
            },
        ),
    ]
