# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 11:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolcalendar',
            name='plaats',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
