# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-11 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolcalendar',
            name='titel',
            field=models.CharField(max_length=250),
        ),
    ]
