# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 12:26
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('schoolcalendar', '0002_schoolcalendar_plaats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolcalendar',
            old_name='einddataum',
            new_name='einddatum',
        ),
        migrations.AlterField(
            model_name='schoolcalendar',
            name='doelgroep',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('KS', 'Kleuters'), ('BS', 'Basisschool'), ('OB', 'Onderbouw'), ('MS', 'Middelbare school'), ('MB', 'Middenbouw'), ('BB', 'Bovenbouw'), ('AA', 'allen')], max_length=20),
        ),
    ]
