# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 10:36
from __future__ import unicode_literals

import bestuur.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bestuur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('tekst', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'bestuur',
            },
        ),
        migrations.CreateModel(
            name='Verslag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(help_text='enkel pdf', upload_to='bestuur/%Y/', validators=[bestuur.validators.validate_file_extension])),
                ('bestuur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bestuursverslag', to='bestuur.Bestuur')),
            ],
        ),
    ]
