# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-20 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_auto_20160920_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['overleden', 'first_name']},
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_email',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='hide_phone',
            field=models.BooleanField(default=False),
        ),
    ]
