# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('werkgroepen', '0001_initial'),
        ('profile', '0003_auto_20160920_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='werkgroep',
            field=models.ManyToManyField(blank=True, related_name='werkgroep', to='werkgroepen.Werkgroep'),
        ),
    ]
