# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_profile_bestuur'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='doelgroep',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('', '-'), ('KS', 'Kleuters'), ('BS', 'Basisschool'), ('OB', 'Onderbouw'), ('MS', 'Middelbare school'), ('MB', 'Middenbouw'), ('BB', 'Bovenbouw'), ('AA', 'allen')], default='', max_length=21),
        ),
        migrations.AddField(
            model_name='profile',
            name='functie',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile/'),
        ),
    ]
