# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-26 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import informatie.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documenten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, help_text='enkel pdf', null=True, upload_to='informatie/%Y/', validators=[informatie.validators.validate_file_extension])),
                ('datum', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Informatie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('tekst', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'informatie',
            },
        ),
        migrations.AddField(
            model_name='documenten',
            name='informatie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='informatie', to='informatie.Informatie'),
        ),
    ]
