# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 11:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adres', models.CharField(blank=True, max_length=255, verbose_name='Straat+huisnr')),
                ('postcode', models.CharField(blank=True, max_length=15, verbose_name='Postcode')),
                ('gemeente', models.CharField(blank=True, max_length=255, verbose_name='Gemeente')),
                ('land', models.CharField(blank=True, default='Belgi\xeb', max_length=255, verbose_name='Land')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('telefoon', models.CharField(blank=True, max_length=50, verbose_name='Telefoon')),
                ('geboortedatum', models.DateField(blank=True, null=True, verbose_name='Geboortedatum')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='nickname')),
                ('aanspreeknaam', models.CharField(blank=True, max_length=255, verbose_name='aanspreeknaam')),
                ('is_ouder', models.BooleanField(default=False)),
                ('is_leerling', models.BooleanField(default=False)),
                ('is_klasouder', models.BooleanField(default=False)),
                ('is_leerkracht', models.BooleanField(default=False)),
                ('is_medewerker', models.BooleanField(default=False)),
                ('parents', models.ManyToManyField(blank=True, related_name='_profile_parents_+', to='myusermodel.Profile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
