# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-25 14:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Werkgroep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=20)),
                ('slug', models.SlugField()),
                ('tekst', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'werkgroepen',
            },
        ),
    ]
